### ISSUE TITLE
[dor-services-app/stage] NoMethodError: undefined method `new' for nil:NilClass

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor-services-app#3422]
## Backtrace

    line 211 of [PROJECT_ROOT]/app/services/cocina/object_creator.rb: default_access_for
    line 116 of [PROJECT_ROOT]/app/services/cocina/object_creator.rb: block in create_dro
    line 111 of [PROJECT_ROOT]/app/services/cocina/object_creator.rb: tap

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/83997809)

**Comment by justinlittman** [comment]
Introduced by https://github.com/sul-dlss/dor-services-app/pull/3411
